modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="slonik"
version="1.0.0"
displayName="Green elephant"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Admin, MCreator"

[[dependencies.slonik]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.slonik]]
    modId="gecholib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

