modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="slonik"
version="1.0.0"
displayName="Green elephant"
credits="Created by SviSvi"
displayURL="https://andrey-golovenhcik.nethouse.ru"
authors="TemanSv1n, Graph_Bober_IV"
description='''
The best russian movie ever
'''

[[dependencies.slonik]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.slonik]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

